# Generated by Django 6.0.4 on 2026-04-28 21:35

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.URLField(blank=True)),
                ("api_key", models.CharField(blank=True, default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MediaSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("path", models.CharField(max_length=500, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TranscodeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "container",
                    models.CharField(blank=True, default="matroska", max_length=120),
                ),
                ("video_codecs", models.JSONField(blank=True, default=list)),
                ("audio_codecs", models.JSONField(blank=True, default=list)),
                ("subtitle_codecs", models.JSONField(blank=True, default=list)),
                ("bitrates", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("absolute_path", models.CharField(max_length=600, unique=True)),
                ("relative_path", models.CharField(max_length=500)),
                ("file_name", models.CharField(max_length=255)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("discovered", "Discovered"),
                            ("transcode_pending", "Transcode pending"),
                            ("transcoding", "Transcoding"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                            ("missing", "Missing"),
                        ],
                        db_index=True,
                        default="discovered",
                        max_length=32,
                    ),
                ),
                ("is_present", models.BooleanField(db_index=True, default=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.datasource",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="core.mediasource",
                    ),
                ),
            ],
            options={
                "ordering": ["stage", "source__name", "relative_path"],
            },
        ),
        migrations.CreateModel(
            name="MediaMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "container_format",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "duration_seconds",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("bitrate", models.BigIntegerField(blank=True, null=True)),
                ("video_codecs", models.JSONField(blank=True, default=list)),
                ("audio_codecs", models.JSONField(blank=True, default=list)),
                ("subtitle_codecs", models.JSONField(blank=True, default=list)),
                ("raw_probe", models.JSONField(blank=True, default=dict)),
                (
                    "extracted_by",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("probed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata_record",
                        to="core.mediafile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranscodeJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_path", models.CharField(default="", max_length=500)),
                ("command", models.TextField(default="")),
                (
                    "priority",
                    models.PositiveSmallIntegerField(db_index=True, default=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("worker", models.TextField(default="")),
                (
                    "media_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="core.mediafile",
                    ),
                ),
                (
                    "transcode_profile",
                    models.ForeignKey(
                        default=core.models.TranscodeProfile.load,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.transcodeprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "priority", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="mediafile",
            constraint=models.UniqueConstraint(
                fields=("source", "relative_path"),
                name="unique_mediafile_per_source_relative_path",
            ),
        ),
    ]
