# Generated by Django 6.0.4 on 2026-04-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcodejob',
            options={'ordering': ['status', 'priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='transcodejob',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='transcodejob',
            name='input_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='transcodejob',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=100),
        ),
        migrations.AlterField(
            model_name='transcodejob',
            name='command',
            field=models.TextField(default=''),
        ),
    ]
