# Generated by Django 6.0.4 on 2026-04-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transcodeprofile",
            name="bitrates",
        ),
        migrations.AddField(
            model_name="transcodeprofile",
            name="bitrate",
            field=models.BigIntegerField(blank=True, default=100000000),
        ),
    ]
