# Generated by Django 6.0.4 on 2026-04-13 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transcodejob_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absolute_path', models.CharField(max_length=600, unique=True)),
                ('relative_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('discovered', 'Discovered'), ('metadata_pending', 'Metadata pending'), ('metadata_ready', 'Metadata ready'), ('transcode_pending', 'Transcode pending'), ('transcoding', 'Transcoding'), ('ready', 'Ready'), ('failed', 'Failed'), ('missing', 'Missing')], db_index=True, default='discovered', max_length=32)),
                ('is_present', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='core.mediasource')),
            ],
            options={
                'ordering': ['stage', 'source__name', 'relative_path'],
            },
        ),
        migrations.AddField(
            model_name='transcodejob',
            name='media_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.mediafile'),
        ),
        migrations.AddConstraint(
            model_name='mediafile',
            constraint=models.UniqueConstraint(fields=('source', 'relative_path'), name='unique_mediafile_per_source_relative_path'),
        ),
    ]
