# Generated by Django 6.0.4 on 2026-04-13 14:15

import django.db.models.deletion
from django.db import migrations, models


def copy_mediafile_metadata(apps, schema_editor):
    MediaFile = apps.get_model("core", "MediaFile")
    MediaMetadata = apps.get_model("core", "MediaMetadata")

    for media_file in MediaFile.objects.all():
        legacy_metadata = getattr(media_file, "metadata", None)
        if not isinstance(legacy_metadata, dict) or not legacy_metadata:
            continue

        MediaMetadata.objects.update_or_create(
            media_file_id=media_file.id,
            defaults={
                "container_format": legacy_metadata.get("container_format", ""),
                "duration_seconds": legacy_metadata.get("duration_seconds"),
                "bitrate": legacy_metadata.get("bitrate"),
                "video_codecs": legacy_metadata.get("video_codecs", []),
                "audio_codecs": legacy_metadata.get("audio_codecs", []),
                "subtitle_codecs": legacy_metadata.get("subtitle_codecs", []),
                "raw_probe": legacy_metadata,
                "extracted_by": legacy_metadata.get("extracted_by", "legacy"),
            },
        )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mediafile_transcodejob_media_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_format', models.CharField(blank=True, default='', max_length=120)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('bitrate', models.BigIntegerField(blank=True, null=True)),
                ('video_codecs', models.JSONField(blank=True, default=list)),
                ('audio_codecs', models.JSONField(blank=True, default=list)),
                ('subtitle_codecs', models.JSONField(blank=True, default=list)),
                ('raw_probe', models.JSONField(blank=True, default=dict)),
                ('extracted_by', models.CharField(blank=True, default='', max_length=120)),
                ('probed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_record', to='core.mediafile')),
            ],
        ),
        migrations.RunPython(copy_mediafile_metadata, reverse_code=noop_reverse),
        migrations.RemoveField(
            model_name='mediafile',
            name='metadata',
        ),
    ]
