# Generated by Django 6.0.4 on 2026-04-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_simplify_media_stages_and_profile_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcodejob',
            name='auto_generated',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
