# Generated by Django 6.0.4 on 2026-04-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_transcodeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcodeprofile',
            name='output_extension',
            field=models.CharField(blank=True, default='.mkv', max_length=16),
        ),
        migrations.AlterField(
            model_name='transcodeprofile',
            name='transcode_audio_codec',
            field=models.CharField(blank=True, default='libopus', max_length=120),
        ),
        migrations.AlterField(
            model_name='transcodeprofile',
            name='transcode_video_codec',
            field=models.CharField(blank=True, default='libsav1', max_length=120),
        ),
    ]
