# Generated by Django 6.0.4 on 2026-04-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_transcodeprofile_output_extension_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transcodeprofile",
            name="output_extension",
        ),
        migrations.RemoveField(
            model_name="transcodeprofile",
            name="transcode_audio_codec",
        ),
        migrations.RemoveField(
            model_name="transcodeprofile",
            name="transcode_ffmpeg_args",
        ),
        migrations.RemoveField(
            model_name="transcodeprofile",
            name="transcode_quality",
        ),
        migrations.RemoveField(
            model_name="transcodeprofile",
            name="transcode_video_codec",
        ),
    ]
