# Generated by Django 6.0.4 on 2026-04-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_transcodeprofile_output_extension_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transcodejob",
            name="auto_generated",
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="stage",
            field=models.CharField(
                choices=[
                    ("discovered", "Discovered"),
                    ("transcode_pending", "Transcode pending"),
                    ("transcoding", "Transcoding"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("missing", "Missing"),
                ],
                db_index=True,
                default="discovered",
                max_length=32,
            ),
        ),
    ]
