# Generated by Django 6.0.4 on 2026-04-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_transcodejob_auto_generated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcodejob",
            name="worker",
            field=models.TextField(default=""),
        ),
    ]
